### ISSUE TITLE
characters like 🇸🇴 are treated as 2 characters

### ISSUE THREAD

**Issue by maddrag0n** [camertron/utfstring#1]
charAt('🇸🇴', 0) is 🇸and charAt('🇸🇴', 1) is 🇴
length('🇸🇴') is 2

**Comment by camertron** [comment]
Hey @maddrag0n, it looks like 🇸🇴  is actually two Unicode codepoints, which is why the library returns 2 for length. I'm not sure why this is, since I thought every Unicode character was supposed to be a single codepoint. I'll do some research and reply in this thread.

**Comment by maddrag0n** [comment]
when dealing with text fields (textarea, input, contenteditable) the OS cursor actually navigates this as 1 char. but interesting enough when you paste 🇸 and directly 🇴 it leads to 🇸🇴. even more interesting if you paste them in reverse order 🇴🇸the OS merges them into one char, even tho they are still displayed as two. backspace actually now deletes both.

**Comment by maddrag0n** [comment]
@camertron check this out: http://www.unicode.org/L2/L2009/09379-n3727-regionalindicators.pdf

**Comment by camertron** [comment]
Ha! Wow that's pretty cool :) Should be relatively straightforward to add support for these "regional indicators."

**Comment by maddrag0n** [comment]
let’s see how many more edge cases they have in store for you 😆

**Comment by camertron** [comment]
Hahaha good call :)

**Comment by camertron** [comment]
I went ahead and refactored a bit, then added support for regional indicators, check it out @maddrag0n: https://github.com/camertron/utfstring/pull/2

**Comment by camertron** [comment]
Merged and published to npm as v1.1.0.

**Comment by maddrag0n** [comment]
works like a charm so far 😄
