### ISSUE TITLE
Add NPM badge to README

### ISSUE THREAD

**Issue by krisztianb** [camertron/utfstring#11]
I don't know on which sites this package is published. But it's definitely on NPM. So it would make it easier for users that find this README page via Google to have a direct link to the NPM page of the package.

Something like this at the top of the file should work:

```md
[![NPM Version](https://img.shields.io/npm/v/typedoc?color=33cd56&logo=npm)](https://www.npmjs.com/package/utfstring)
```

**Comment by camertron** [comment]
I tried adding the badge you suggested but it shows version 0.23.10 instead of the current version, 2.0.2. Do you know why that is? I was unable to find any documentation on shields.io for the /v/typedoc URL.

**Comment by krisztianb** [comment]
LOL, my bad. You need to replace "typedoc" with "utfstring". Typedoc is the GIT repo I copied the line from.

**Comment by camertron** [comment]
Ahhh ok thanks! Just added 😄
