### ISSUE TITLE
Version 3.0.0 is not functional

### ISSUE THREAD

**Issue by krisztianb** [camertron/utfstring#13]
Hi Cameron.

I think you forgot to run the build before you published the package.
One must run `npm build` so that the JavaScript files are generated before `npm publish`.

Could you please fix this and publish a new version? It would also make sense to unpublish this version since it is broken.

To prevent this from happening in the future I see two options:

- **Manual:** I personally run the tests and the build before publishing and also do an `npm pack`. This generates a local file with the exact files that would get published. Then you can verify on your own if the content of the package is correct.
- **Automatic:** One can add a pre-publish script to the `package.json` that runs tests and the build before publishing the package.

**Comment by camertron** [comment]
Hey @krisztianb, sorry about that! I missed the fact that the `dist/` directory is not checked into source control.

Unfortunately npm won't let me unpublish v3.0.0, so I've just published v3.0.1 instead. Apologies for the confusion.

A pre-publish script sounds good to me, assuming it will fail to publish if the build fails.

**Comment by krisztianb** [comment]
Thanks for fixing this.

If unpublishing does not work maybe you can [deprecate](https://docs.npmjs.com/cli/v8/commands/npm-deprecate) it instead?

**Comment by camertron** [comment]
I thought about that, but deprecation isn't really what I want. It's not deprecated, it's broken. But whatever, I guess deprecation is better than nothing.
