### ISSUE TITLE
IndexOf() with start position is not working correctly

### ISSUE THREAD

**Issue by FlorianSchwingenschloegl** [camertron/utfstring#17]
**Found in Version: 3.0.1**
The `UtfString.indexOf()` function is not working correctly if a certain start index is used.

To reproduce this issue you can do following:

```javascript
new UtfString("This is a Text!").indexOf("t",15)  // => Output: 13
```

compared to

```javascript
"This is a Text".indexOf("t",15)  // => Output: -1
```

Seems like the `indexOf` function starts to search from the start of the string again. I would expect it to return -1 if start position is equal or higher than the length of the text.

**Comment by camertron** [comment]
Hey @FlorianSchwingenschloegl, thanks for bringing this to my attention. I found the bug and have published v3.1.1 with the fix 😄
