### ISSUE TITLE
node imports wrong in docs

### ISSUE THREAD

**Issue by maddrag0n** [camertron/utfstring#3]
actual imports (when installing from npm with `npm i --save utfstring`) are:

- ES6: `import { UtfString } from 'utfstring/utfstring.js';`
- ES5: `var UtfString = require('utfstring/utfstring.js').UtfString;`

they sure are not pretty 😂
- a clean ES6 import usually looks like `import UtfString from 'utfstring';`, so you can actually do stuff like `import { length as utfLength, stringToCodePoints } from 'utfstring';`
- a clean ES5 import usually looks like `var UtfString = require('utfstring');`

**Comment by camertron** [comment]
You have uncovered the fact that I'm really not a Javascript guy 😉 . UtfString just uses `module.exports`, is there a better way?

**Comment by maddrag0n** [comment]
tbh I am more of a npm user than a module dev 😇. also I am way better with the ES6 syntax for exports.

also I am mostly using NodeJS… that said, here is a couple of things, that I think will solve these issues

1. move every method into its own file, this will most likely result in smaller bundle sizes for projects, that only use some methods (enabling `import stringToCodePoints from 'utfstring/stringToCodePoints';` style imports)
1. add an index.js that requires and exports the stuff you want to expose (make sure it has a main export for the entire package and one for every method that gets exposed)
1. add the `index.js` as value of key `main` in package.json

afaik that should solve most issues. you might want to have  a look how other projects handle this. [acdlite/recompose](https://github.com/acdlite/recompose) is a good example.

**Comment by camertron** [comment]
@maddrag0n ok, I think I've figured out how to make `require` easier, see https://github.com/camertron/utfstring/pull/4.

Not sure how to break up the lib so each function lives in a separate file, since there are a number of shared functions that I'd have to duplicate a bunch of times. Plus the lib isn't very large.

**Comment by camertron** [comment]
Just released v1.2.0 to npm that corrects the `require` issue. Still not sure what to do about breaking the lib up. Nobody seems to be replying so I'm going to close this issue.
