### ISSUE TITLE
Add TypeScript type declarations?

### ISSUE THREAD

**Issue by krisztianb** [camertron/utfstring#8]
Hi. Thank you for your library.

Would you be interested in adding [type declarations for TypeScript](https://www.typescriptlang.org/docs/handbook/2/type-declarations.html) to this project? This would make the usage of the library type-safe in TypeScript projects.

If so I could create a PR for this. If not I will create a PR for it in the [DefinitelyTyped repo](https://github.com/DefinitelyTyped/DefinitelyTyped) and users will have to install the type declarations separately.

Adding the type declarations to this repo is the preferred solution.

**Comment by sant123** [comment]
I created a fork some time ago for Deno and written in Typescript. https://github.com/sant123/utfstring maybe it could be useful for you.

**Comment by camertron** [comment]
Hey @krisztianb I would absolutely welcome a PR to add type declarations, that would be awesome! I also wouldn't be opposed to converting utfstring over to TypeScript, although I imagine that would be more work.

**Comment by sant123** [comment]
@camertron it was more work but is worth it. Would be more that happier that you take https://github.com/sant123/utfstring merge it and deprecate my repository. Basically you are the owner of all the logic stored there 😄

**Comment by camertron** [comment]
Hey @sant123. What specifically did you have to change to make the lib work with Deno? If it's backwards-compatible with Javascript, I'd be more than happy to review a PR :)

**Comment by sant123** [comment]
Hey @camertron, curiously there was some news from Deno and they plan to support current npm modules with an experimental feature they just released. https://deno.com/blog/v1.25#experimental-npm-support

Perhaps this would be the key to support this library in Deno. Let's see what happens 👀
