### ISSUE TITLE
Make UtfString non-static

### ISSUE THREAD

**Issue by krisztianb** [camertron/utfstring#9]
Is there any reason why UtfString is a static class?

I think it would make sense to write code like this:

```js
const utfStr = new UtfString("a string in which some letters can't be represented by a JavaScript standard utf-16 string");
console.log(utfStr.length);
const anotherUtfStr = utfStr.substr(0, 5);
```

This makes it easier to spot parts of your code that are UTF-32 aware and those that are not.

**Comment by camertron** [comment]
Hey @krisztianb, that's an interesting question. I experimented with an approach like that when I was first writing the library, but decided it added too much overhead. It probably wouldn't be difficult to add support for `UtfString` instances though. I'd be happy to review a pull request if you'd like to submit one.

**Comment by krisztianb** [comment]
I started working on this. Obviously this change breaks most of the tests. Would you be interested in a review before the tests are updated? I think that would be a reasonable approach.

**Comment by camertron** [comment]
@krisztianb would it be possible to keep the existing functionality (and corresponding tests) _and_ add support for a `UtfString` class? If so, then I imagine you'd only need to add new tests for the new functionality.

**Comment by krisztianb** [comment]
Sounds reasonable as it makes it easier for existing users to update their code.

However I would like to move the "visual" property into a separate class. What do you think about that?

**Comment by krisztianb** [comment]
This is the WOP branch if you want to take a look: https://github.com/krisztianb/utfstring/tree/non-static-2

I'm interested in your feedback before I put more effort into this.

**Comment by camertron** [comment]
> However I would like to move the "visual" property into a separate class. What do you think about that?

Yeah that makes sense to me 👍 

> This is the WOP branch if you want to take a look... I'm interested in your feedback before I put more effort into this.

I just had a look and I think what you've got is excellent! I like how the old functionality is still attached to the same export via `static` functions. Is there anything else you need to do before submitting a PR?

**Comment by krisztianb** [comment]
Thanks. I still have to write all the missing non-static methods before I can submit a PR.

Currently the non-static version of the class simply wraps a string and all the non-static methods call the static methods with that string. This way you don't have to duplicate any code.

Another approach would be not to use your regular expression solution for finding surrogate pairs and instead let JavaScript's [string iterator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/@@iterator#description) do it for you.

So instead of storing the string and calling the static methods we could store an array of characters and work with those. So the constructor of `UtfString` could do this:

```ts
constructor (unsafeString: string) {
    this.characters = [...unsafeString];
}
```

For the string `'A\uD835\uDC68'` this would create an internal `characters` array with two entries: `A` and `'\uD835\uDC68'`.
This has the benefit of not having to use any regular expressions. However we would have to rewrite every non-static method so that it uses this internal array instead of calling the static methods.

Or we rewrite the static methods to use the array. But that way you lose the ability to derive `UtfVisualString` from `UtfString` because the iterator splits up grapheme clusters. So for `UtfVisualString` you will still need the regular expression solution.

What do you think?

**Comment by camertron** [comment]
> Thanks. I still have to write all the missing non-static methods before I can submit a PR.

Ah ok I was wondering about that 👍 

> Currently the non-static version of the class simply wraps a string and all the non-static methods call the static methods with that string. This way you don't have to duplicate any code.

Yeah I like that approach.

> Another approach would be not to use your regular expression solution for finding surrogate pairs and instead let JavaScript's [string iterator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/@@iterator#description) do it for you.

Oh wow I had no idea that existed! I'm not really much of a Javascript dev 🥴

> What do you think?

Since it's not possible to get grapheme clusters via their index (i.e. via `[]` or `charAt`), it would seem our only two options are the regex-based approach or an array of characters. I'm hesitant to duplicate the string by turning it into an array, so I think we should stick with the regex approach. As with so many problems, the tradeoff is between computation time and memory usage. I'm ok choosing more CPU time, at least for now; I haven't heard anyone asking for the lib to be more performant (yet).

However that string iterator thing has me wondering... if Javascript can now iterate over grapheme clusters, can it also identify grapheme boundaries? If so, maybe UtfString can be rewritten or obviated entirely.

**Comment by krisztianb** [comment]
> However that string iterator thing has me wondering... if Javascript can now iterate over grapheme clusters, can it also identify grapheme boundaries? If so, maybe UtfString can be rewritten or obviated entirely.

The docs say that `Strings are iterated by Unicode codepoints. This means grapheme clusters will be split, but surrogate pairs will be preserved.` Which means that we could use the iterator for `UtfString` but not for `UtfVisualString` as the prupose of that class is to preserve grapheme clusters. Or am I mistaken?

**Comment by camertron** [comment]
Right yeah I saw that in the docs. The vast majority of the code inside UtfString was needed in previous versions of Javascript specifically because there was no way to iterate over codepoints wider than 16 bits, i.e. surrogate pairs. I'm not even sure it's correct to call the two halves of a surrogate pair "codepoints" because the UTF standard maps _single_ discreet integer values to characters. In other words my understanding is that a codepoint cannot be made up of multiple values.

The "visual" UtfString class will still be necessary, but if the built-in iterator preserves surrogate pairs, there's not much other work to do.

**Comment by krisztianb** [comment]
I still like the idea of creating a separate `UtfString` class because it enables you to use the ordinary string methods without having to think about UTF32 chars. Only the iterator solves that problem for the normal string type. All other methods for example `charAt(i)` don't take them into account. So you will always have to use the iterator which is quite painful imho.

I think I'll stick to the regular expression solution in `UtfString` as well.

**Comment by krisztianb** [comment]
Just to give you an update: We are planning to use this library in one of our projects at our company. Another collague of mine joined and we are adding missing string methods and unit tests. But we will have to ask management if they allow us to push our changes into the public package.

We also tested the performance of the regular expression solution vs. the for-of array solution and the regular expression solution is the faster one.

I'll keep you posted.

**Comment by camertron** [comment]
> Only the iterator solves that problem for the normal string type. All other methods for example `charAt(i)` don't take them into account. So you will always have to use the iterator which is quite painful imho.

Yes, I agree.

> But we will have to ask management if they allow us to push our changes into the public package.

Ok makes sense, and thanks for the update :)

> We also tested the performance of the regular expression solution vs. the for-of array solution and the regular expression solution is the faster one.

Wow I'm surprised! I guess the extra memory isn't worth it, good to know!
